config/routes.rb
Rails.application.routes.draw do
  resources :applications, only: [:new, :create]
  root to: "applications#new"
  mount Optimadmin::Engine => "/admin"
end
Optimadmin::Engine.routes.draw do
  resources :applications, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
end

app/models/application.rb
class Application < ActiveRecord::Base

  mount_uploader :cv, CvUploader

  #validates :name, :grade, :speciality, :email, :phone_number, :date, :cv, presence: true

  HOW_HEARD = ['Doctors.net', 'BMJ.com', 'Facebook', 'LinkedIn', 'Other']
end

app/models/concerns/menu_resourceable.rb
module MenuResourceable
  extend ActiveSupport::Concern

  included do
    has_many :links, class_name: "Optimadmin::Link", as: :menu_resource
    has_many :menu_items, class_name: "Optimadmin::MenuItem", through: :links
  end

  def menu_names
    menu_items.pluck(:menu_name)
  end

  def side_menus
    side_menu_names.map{|menu_name| Optimadmin::Menu.new(name: menu_name) }
  end

  def side_menu_names
    menu_names.reject{|x| %w(header footer).include?(x) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :global_site_settings

  private

  def global_site_settings
    @global_site_settings ||= Optimadmin::SiteSetting.current_environment
  end
  helper_method :global_site_settings
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def new
    @application = Application.new
  end

  def create
    @application = Application.new(application_params)
    if @application.save
      ApplicationMailer.application_created(global_site_settings, @application).deliver_now
      redirect_to root_path, notice: "Thank you for your application"
    else
      render :new
    end
  end

  private

  def application_params
    params.require(:application).permit!
  end
end

app/controllers/optimadmin/applications_controller.rb
module Optimadmin
  class ApplicationsController < Optimadmin::ApplicationController
    before_action :set_application, only: [:show, :edit, :update, :destroy]

    def index
      @applications = Optimadmin::BaseCollectionPresenter.new(collection: Application.where('title ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ApplicationPresenter)
    end

    def show
    end

    def new
      @application = Application.new
    end

    def edit
    end

    def create
      @application = Application.new(application_params)
      if @application.save
        redirect_to applications_url, notice: 'Application was successfully created.'
      else
        render :new
      end
    end

    def update
      if @application.update(application_params)
        redirect_to applications_url, notice: 'Application was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @application.destroy
      redirect_to applications_url, notice: 'Application was successfully destroyed.'
    end

  private


    def set_application
      @application = Application.find(params[:id])
    end

    def application_params
      params.require(:applications).permit(:name, :grade, :speciality, :email, :phone_number, :date, :additional_information, :cv)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/_form.html.erb
<%= form_for @application do |f| %>
  <%= field_set_tag "Your Details" do %>

    <% if @application.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize @application.errors.count, "error" %> prevented your application from being sent</h2>

        <ul>
          <% @application.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="small-12 columns field first">
        <%= f.text_field :name, placeholder: "Name" %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-4 columns field">
        <%= f.text_field :grade, placeholder: "Grade" %>
      </div>
      <div class="small-12 medium-4 columns field">
        <%= f.text_field :speciality, placeholder: "Speciality" %>
      </div>
      <div class="small-12 medium-4 columns field">
        <%= f.text_field :date, placeholder: "Date available for locums" %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-4 columns field">
        <%= f.email_field :email, placeholder: "Email" %>
      </div>
      <div class="small-12 medium-4 columns field">
        <%= f.text_field :phone_number, placeholder: "Tel" %>
      </div>
      <div class="small-12 medium-4 columns field">
        <%= f.file_field :cv %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-4 columns field">
        <%= f.select :how_heard, options_for_select(Application::HOW_HEARD), prompt: 'How did you hear about this offer?' %>
      </div>
      <div class="small-12 medium-8 columns field">
        <%= f.text_field :how_heard_other, placeholder: "Please tell us how you heard about this offer if you selected 'Other' from the previous drop down" %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns field">
        <%= f.text_area :additional_information, placeholder: "Additional Information" %>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/new.html.erb
<% unless @application.errors.any? %>
  <div class="row">
    <div class="small-12 columns">
      <%= image_tag "banner.jpg", alt: "Register with Recruit4Health today and you can receive a bonus of &pound;1000!", class: 'banner' %>
    </div>
  </div>

  <div class="row content">
    <div class="small-12 columns">
        <% if flash.present? %>
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, class: "#{name} flash-message" %>
          <% end %>
        <% end %>

      <h1>
        Recruit4Health is offering a &pound;1000 registration bonus to all NHS Locum Doctors that work for Recruit4Health.
      </h1>

      <p>
        Specialising in the healthcare sector,Recruit4Health is contracted to supply NHS Locum doctor roles throughout the UK,
        in particular the North West, Yorkshire, East and South East
      </p>

      <ul>
        <li>
          Recruit4Health has locum NHS doctor roles in all grades and specialties
        </li>
        <li>
          Recruit4Health has hundreds of locum vacancies - full time work or ad hoc shifts
        </li>
      </ul>

      <p>
        To see if you qualify to register with us, please fill out the form below and attach your most recent CV.
        Please note that due to the quantity of application we receive, we will only contact you if your application has been successful
      </p>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="small-12 columns">
    <%= render "form" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="small-12 columns">
      <p>Recruit4Health NHS Locum Doctor Registration Bonus Terms & Conditions</p>
      <p>The Recruit4Health NHS Locum Doctor Registration Bonus scheme and the terms and conditions constitute the entire agreement between the parties. In the event of conflict between this NHS Locum Doctor Registration Bonus scheme and the terms and conditions, the terms and conditions shall prevail. The Recruit4health NHS Locum Doctor Registration Bonus scheme and these terms and conditions refer to any instances of a valid candidate Registration for Recruit4health.</p>

      <ul>
        <li>The new bonuses outlined below are effective as of the 10th August 2015. Any registrations made before this will not be eligible for the bonus.</li>
        <li>Excludes candidates that are already registered with Recruit4health and actively seeking work. </li>
        <li>To qualify for a reward, you must be fully registered and have sent all necessary paperwork to CCS framework standards within 4 weeks of initial enquiry and placed within a 6 month period.</li>
        <li>Once placed in a role or assignment through Recruit4health, the referrer will be eligible for their bonus only after the referee has completed 700 hours NHS Locum work.</li>
        <li>The above hours must be completed within 12 months of you being activated to work with Recruit4health to be eligible for your bonus.</li>
        <li>If you leave Recruit4health prior to completing the hours outlined above or prior to the 12 months and then attempt to re-activate their registration you will not be eligible for your bonus.</li>
        <li>Applicants must have experience working in the NHS.</li>
        <li>Upon your successful registration and completion of 700 hours, you will receive up to £1000.</li>
        <li>Recruit4health reserves the right to offer an alternative reward of the same value at any time.</li>
        <li>You will be responsible for the payment of Income tax and National Insurance on all monies received.</li>
        <li>Recruit4health’s decision is final.</li>
      </ul>

      <p>Nothing in this agreement shall limit or exclude any party's liability for fraud or for death or personal injury caused by the negligence, or to the extent otherwise not permitted by law.</p>

    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= global_site_settings['Name'] %></title>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<header class="row">
  <div class="small-12 columns">
    <div class="red">
      <div class="row">
        <div class="small-7 columns">
          <%= image_tag "logo.jpg", alt: global_site_settings['Name'], title: global_site_settings['Name'] %>
        </div>
        <div class="small-5 columns">
          <p>
            Specialist healthcare recruitment
          </p>
          
          <p class="call">
            <% unless global_site_settings["Phone"].blank? %>
              Call today: <%= global_site_settings["Phone"] %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>
<body>
  <%= render "layouts/header" %>

  <%= yield %>

  <%= render "layouts/footer" %>
</body>
</html>

app/views/optimadmin/applications/_application.html.erb
<div class="row collapse module-list-index <%= cycle('odd', 'even') %>" data-equalizer="module-list" id="item_<%= application_presenter.id %>">
  <div class="large-1 small-2 columns" data-equalizer-watch="module-list">
    <%= application_presenter.detail_toggle_link %>
  </div>

  <div class="large-5 small-6 columns" data-equalizer-watch="module-list">
    <%= application_presenter.title %>
  </div>

  

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= application_presenter.toggle_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= application_presenter.show_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= application_presenter.edit_link %>
  </div>

  <div class="large-1 hide-for-medium-down columns last" data-equalizer-watch="module-list">
    <%= application_presenter.delete_link %>
  </div>

  <div class="row module-list-detail hide" id="index-list-<%= application_presenter.id %>">
    <div class="small-12 columns module-list-summary last">

    </div>
  </div>
</div>

app/views/optimadmin/applications/_form.html.erb
<%= form_for(application) do |f| %>
<% if application.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

    <ul>
      <% application.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  

  <div class="tabs prevent-flash">
    <ul class="tab-list">
      <li><a href="#tabs-1">Content</a></li>
      <li><a href="#tabs-2">Media</a></li>
      <li><a href="#tabs-3">Settings</a></li>
      <li>
        <%= link_to '#', class: 'destroy-tabs right', data: { class: 'tabs' } do %>
          <%= octicon('chevron-down') %>
        <% end %>
      </li>
    </ul>

    <%= field_set_tag nil, id: 'tabs-1' do %>
            <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
            <div class="field">
        <%= f.label :grade %><br>
        <%= f.text_field :grade %>
      </div>
            <div class="field">
        <%= f.label :speciality %><br>
        <%= f.text_field :speciality %>
      </div>
            <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
            <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number %>
      </div>
            <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>
            <div class="field">
        <%= f.label :additional_information %><br>
        <%= f.text_area :additional_information, class: 'tinymce' %>
      </div>
            <div class="field">
        <%= f.label :cv %><br>
        <%= f.text_field :cv %>
      </div>
          <% end %>

    <%= field_set_tag nil, id: 'tabs-2' do %>
      
          <% end %>

    <%= field_set_tag nil, id: 'tabs-3' do %>
          <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/optimadmin/applications/edit.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Edit Application' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: applications_path, title: 'Application' %>

  <%= render 'form', application: @application %>
</div>

app/views/optimadmin/applications/index.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Manage Applications' %>

<div class="main-content">
  <div class="row module-header collapse">
    <%= render 'optimadmin/shared/module/index/new_item', title: 'Application', object: Application, path: new_application_path %>
    <%= render 'optimadmin/shared/search_form' %>
    <%= render 'optimadmin/shared/module/index/pagination' %>
    <!--
      <%= render 'optimadmin/shared/module/index/order', options: [['Username', 'username']] %>
    -->
    <%= render 'optimadmin/shared/module/index/recycle_bin', items: @applications.size, path: root_url %>
  </div>

  <div class="row collapse module-list-index header">
    <%= list_item 'large-1 small-2' do %>
      <%= link_to octicon('chevron-down'), '#', class: 'helper-link index-list-expand-all', data: { this_class: 'octicon-chevron-up octicon-chevron-down' } %>
    <% end %>

    <%= list_item 'large-5 small-4' do 'Title' end %>

    <%= list_item 'large-2 hide-for-medium-down' do 'Image' end %>

    <%= list_item { 'Display' } %>
    <%= list_item { 'View' } %>
    <%= list_item { 'Edit' } %>

    <%= list_item 'large-1 hide-for-medium-down text-center last' do 'Delete' end %>
  </div>

  <%= render partial: 'application', collection: @applications, as: :application_presenter %>
  <%= paginate @applications %>
</div>

app/views/optimadmin/applications/new.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'New Application' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: applications_path, title: 'Application' %>

  <%= render 'form', application: @application %>
</div>

app/views/optimadmin/shared/sidebar/_module_links.html.erb
<div class="content-categories-sidebar">
  <div class="row collapse">
    <div class="small-8 show-for-medium-down columns">
      <%= link_to octicon('book') + 'Manage Content',
          '#',
          class: 'content-categories-toggle toggle-class',
          data: {
            class: 'content-categories-toggle-visiblity',
            container: '.content-categories, .content-categories-toggle',
            return: 'true'
          } %>
    </div>
    <div class="small-4 show-for-medium-down columns">
      <%= link_to logout_path, class: 'logout-link' do %>
        <%= octicon('sign-in') %> Logout
      <% end %>
    </div>
  </div>

  <div class="row collapse">
    <div class="large-12 small-8 left content-categories columns">
      <div class="content-category-type">
        Manage Your Content
      </div>

      <ul class="content-category-list">
        <% if can? :manage, Optimadmin::MenuItem %>
          <li><%= link_to 'Site Navigation', menu_items_path %></li>
        <% end %>
      </ul>

      <div class="content-category-type">
        Website Visuals
      </div>

      <ul class="content-category-list">

      </ul>
    </div>
  </div>
</div>